services:
  backend:
    build: ./app/backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/familycalendar
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: familycalendar
    volumes:
      - ./app/db-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/html:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge